name: Scorecard supply-chain security
on:
  # For Branch-Protection check. Only the default branch is supported. See
  # https://github.com/ossf/scorecard/blob/main/docs/checks.md#branch-protection
  branch_protection_rule:
  # To guarantee Maintained check is occasionally updated. See
  # https://github.com/ossf/scorecard/blob/main/docs/checks.md#maintained
  schedule:
    - cron: '26 7 * * 0'
  push:
    branches: [ main ]

# Declare default permissions as read only.
permissions: read-all

jobs:
  analysis:
    name: Scorecard analysis
    runs-on: ubuntu-latest
    permissions:
      # Needed to upload the results to code-scanning dashboard.
      security-events: write
      # Needed to query private dependencies.
      packages: read
      # Needed to publish results to the scorecard GitHub Action.
      id-token: write
      # Read for repo contents API.
      contents: read
    steps:
      - name: "Checkout code"
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          persist-credentials: false
      - name: "Run analysis"
        uses: ossf/scorecard-action@dc50aa9510b46c811795eb24b2f1ba02a914e534 # v2.3.3
        with:
          results_file: results.sarif
          results_format: sarif
          # (Optional) "publish_results" will trigger a "SARIF file" to be
          # uploaded to the "Code Scanning" tab of the repository.
          publish_results: true
      # Upload the results as a SARIF file to the "Code Scanning" tab.
      - name: "Upload artifact"
        uses: actions/upload-artifact@6b11ca4d2ae66b385c16a9d1b2bb3c0babf3f8b1 # v4.2.6
        with:
          name: SARIF file
          path: results.sarif
          if-no-files-found: error
      - name: "Upload to code-scanning"
        if: github.event_name != 'pull_request'
        uses: github/codeql-action/upload-sarif@dd903d2e4f5405488e5ef1422510ee31c8b32357 # v3.36.2
        with:
          sarif_file: results.sarif
